### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by brunovolko** [rcastill/SpamBot#1]
Hello, how are you?
I'd like to try your bot. The code seems great, nice job.
How do you use it? Maybe a readme file with instructions would be perfect (in case you want to open the project to the community).

**Comment by rcastill** [comment]
So, I have totally forgotten this repo. It was a joke between friends. I updated the README and added a kickstart script in case you want to take a look. I **did not** update any core functionality, nor the telegram bot api version (2017 old).

**Comment by devildarkpro** [comment]
Plz Make a tutorial

**Comment by rcastill** [comment]
Hi @devildarkpro, did you read the README?
